const localhostLocation = {
    geonames_id: 1141909415,
    latitude: 21.307796478271484,
    longitude: -157.85919189453125,
    zip: '96801',
    continent: {
      code: 'NA',
      name: 'North America',
      name_translated: 'North America',
      geonames_id: 6255149,
      wikidata_id: 'Q49'
    },
    country: {
      alpha2: 'US',
      alpha3: 'USA',
      calling_codes: [ '+1' ],
      currencies: [ [Object] ],
      emoji: '🇺🇸'  ,
      ioc: 'USA',
      languages: [ [Object] ],
      name: 'United States',
      name_translated: 'United States',
      timezones: [
        'America/New_York',
        'America/Detroit',
        'America/Kentucky/Louisville',
        'America/Kentucky/Monticello',
        'America/Indiana/Indianapolis',
        'America/Indiana/Vincennes',
        'America/Indiana/Winamac',
        'America/Indiana/Marengo',
        'America/Indiana/Petersburg',
        'America/Indiana/Vevay',
        'America/Chicago',
        'America/Indiana/Tell_City',
        'America/Indiana/Knox',
        'America/Menominee',
        'America/North_Dakota/Center',
        'America/North_Dakota/New_Salem',
        'America/North_Dakota/Beulah',
        'America/Denver',
        'America/Boise',
        'America/Phoenix',
        'America/Los_Angeles',
        'America/Anchorage',
        'America/Juneau',
        'America/Sitka',
        'America/Metlakatla',
        'America/Yakutat',
        'America/Nome',
        'America/Adak',
        'Pacific/Honolulu'
      ],
      is_in_european_union: false,
      fips: 'US',
      geonames_id: 85633793,
      hasc_id: 'US',
      wikidata_id: 'Q30'
    },
    city: {
      fips: null,
      alpha2: null,
      geonames_id: 1141909415,
      hasc_id: null,
      wikidata_id: 'Q18094',
      name: 'Honolulu',
      name_translated: 'Honolulu'
    },
    region: {
      fips: 'US15',
      alpha2: 'US-HI',
      geonames_id: 85688671,
      hasc_id: 'US.HI',
      wikidata_id: 'Q782',
      name: 'Hawaii',
      name_translated: 'Hawaii'
    }
  };

  export default localhostLocation;